### ISSUE TITLE
npm issues

### ISSUE THREAD

**Issue by mderrick** [chaijs/chai-spies#43]
I just installed via `npm install chai-spies` as documented and noticed I have installed [this NPM package](https://www.npmjs.com/package/chai-spies) which is not this repository.

Strangely I can also see that they are both are the same version `0.7.1` even though the one I have installed lacks some of the functionality that the readme documents.

I think you might need to publish to NPM again!
Thanks

**Comment by keithamus** [comment]
Hey @mderrick thanks for the issue!

`master` is typically ahead of the released version. The [0.7.1](https://github.com/chaijs/chai-spies/commits/0.7.1) tag reflects the currently published code to npm. You can see [here is the new code that has yet to be released](https://github.com/chaijs/chai-spies/compare/0.7.1...master). 

Rest assured we'll make a new release soon!

I'll close this issue - because everything is underway, we just need some time to make a new release :smile:

**Comment by mderrick** [comment]
Ah! OK. It was the version number that threw me off. I was banging my ahead against the wall on this one. Thanks for the update. I will hold off on using `chai.spy.returns` for now :+1:
