### ISSUE TITLE
How to return fake data from spy.on(obj, 'funcName') when called ?

### ISSUE THREAD

**Issue by narainsagar** [chaijs/chai-spies#48]
I don't know is there any function or not!
Please let me know is it possible?

Something like that:
```spy(obj, 'funcName').and.returnValue(5);`  // spy will return a fake data when called```

**Comment by scaljeri** [comment]
+1 I would really like to know this too!

**Comment by lucasfcosta** [comment]
Hello guys, thanks for the issue!
For what I can see chai-spies is not able change the return value of a function. Chai's focus is actually doing assertions, so you can only run things related to assertions on spies.
To create stubs for your functions you can use [SinonJS](http://sinonjs.org/docs/).

**Comment by keithamus** [comment]
Hey @narainsagar @scaljeri and @lucasfcosta :smile: 

Right now the `spy.on` API doesn't allow you to override the functionality. Some discussion has gone on about this in #38 (see https://github.com/chaijs/chai-spies/issues/38#issuecomment-172854270). The alternatives so far are:

```js
Array.prototype.push = chai.spy(function () { return undefined });
Array.prototype.push = chai.spy.returns(undefined);
Array.prototype.push = function () { return undefined; }
chai.spy.on(Array.prototype, 'push');
```

We've discussed before about having extra methods on the spy interface, but we'd like to move away from that (#38 has some on this, as does this comment in #35: https://github.com/chaijs/chai-spies/pull/35#issuecomment-125111547). 

I'll close this, because it's on the radar and will likely come as a result of #38. If you want to help out, continuing the discussion there would be awesome!
