### ISSUE TITLE
How to check `with` in recursion calls?

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [chaijs/chai-spies#50]
Hey guys,

How can I use `to.have.been.called.with`? I have a function, which in case of receiving an array as data param, calls itself array.length times.

Like this:

```
        var spy = chai.spy.on(dataHandler.pubsub, 'emit');
        var data = [
          {id: 123123, a: true, f: 'match'},
          {id: 232323, a: true, f: 'event'},
          {id: 511515, a: false, f: 'lineups'}
        ];
        var promise = dataHandler.save('match', data); // dataHandler.pubsub.emit is called within
        expect(spy).to.have.been.called.exactly(3); // ok
        expect(spy).to.have.been.called.with(->> HOW??? <<-);
```

Thanks.

**Comment by keithamus** [comment]
Hey @AlexanderTserkovniy thanks for the issue.

As [per the docs](https://github.com/chaijs/chai-spies#with), `.called.with()` takes an argument set that matches the argument set of the called function. Each call is mapped, and `.called.with` asserts that _one of those calls_ has a matching argument set to itself; for example:

```js
spy('a', 'b', 'c');
spy('d', 'e', 'f');
expect(spy).to.have.been.called.with('d', 'e', 'f');
expect(spy).to.have.been.called.with('a', 'b', 'c');
```

I hope this helps, but if not you'd have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.
